services:
  ekoru:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: ekoru
    ports:
      - "3002:3000"
    networks:
      - ekoru-network
    env_file:
      - .env.local

networks:
  ekoru-network:
    external: true
