services:
  ekoru:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: ekoru
    ports:
      - "8000:3000"
    networks:
      - ekoru-network
    env_file:
      - .env.local
    deploy:
      resources:
        limits:
          cpus: "1.0" # Maximum 1 CPU core
          memory: 512M # Maximum 512MB RAM
        reservations:
          cpus: "0.5" # Minimum 0.5 CPU cores reserved
          memory: 256M # Minimum 256MB RAM reserved
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:3000",
        ]
      interval: 60s
      timeout: 5s
      retries: 2
      start_period: 30s

networks:
  ekoru-network:
    external: true
