version: "0.2"
ignorePaths: []
dictionaryDefinitions:
  - name: custom-dictionary
    path: ./.cspell/custom-dictionary.txt
    addWords: true
dictionaries:
  - custom-dictionary
words:
  - desconexión
  - ekoru
  - Linkedin
ignoreWords:
  - PROXIMAMENTE
  - Politica
  - Terminos
  - ecommerce
  - linkedin
  - turbopack
  - youtube
import: []
